featureFlags:
  flags:
  - flag:
      name: Jan Flag
      identifier: Jan_Flag
      description: ""
      permanent: false
      spec:
        type: boolean
        default:
          onVariation: "false"
          offVariation: "false"
        variations:
        - identifier: "true"
          value: "true"
        - identifier: "false"
          value: "false"
      environments:
      - identifier: E1
        default:
          onVariation: "false"
          offVariation: "false"
        state: "on"
  - flag:
      name: XYZ Flag
      identifier: XYZ_Flag
      description: ""
      permanent: false
      spec:
        type: boolean
        default:
          onVariation: "false"
          offVariation: "false"
        variations:
        - identifier: "true"
          value: "true"
        - identifier: "false"
          value: "false"
      tags:
      - tag:
          name: tag1
          identifier: tag1
      environments:
      - identifier: E1
        default:
          onVariation: "false"
          offVariation: "false"
        state: "off"
  projectIdentifier: Kira_Test
  orgIdentifier: default
